-- GERADO por gen_produtos.py. Reseed do catalogo (apaga e reinsere).
delete from itens_pedido where produto_id is not null;
delete from produtos;
delete from categorias;
insert into categorias (nome, ordem) values
  ('Vasos', 1),
  ('Luminárias', 2),
  ('Animais', 3),
  ('Estátuas', 4),
  ('Quadros', 5),
  ('Organizadores', 6),
  ('Presentes', 7),
  ('Vasos de plantas', 8);
insert into produtos (categoria_id, nome, preco, foto_url, sku, material) values
  ((select id from categorias where nome='Vasos'), 'Nova pasta', 59, '/produtos/vasos-nova-pasta.webp', 'vasos-nova-pasta', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vase Vorticia', 59, '/produtos/vasos-vase-vorticia.webp', 'vasos-vase-vorticia', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso', 59, '/produtos/vasos-vaso.webp', 'vasos-vaso', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso 2', 59, '/produtos/vasos-vaso-2.webp', 'vasos-vaso-2', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso 3', 59, '/produtos/vasos-vaso-3.webp', 'vasos-vaso-3', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso 4', 59, '/produtos/vasos-vaso-4.webp', 'vasos-vaso-4', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Axis', 59, '/produtos/vasos-vaso-axis.webp', 'vasos-vaso-axis', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Brisa', 59, '/produtos/vasos-vaso-brisa.webp', 'vasos-vaso-brisa', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Diamante', 59, '/produtos/vasos-vaso-diamante.webp', 'vasos-vaso-diamante', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Diara', 59, '/produtos/vasos-vaso-diara.webp', 'vasos-vaso-diara', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Encastra', 59, '/produtos/vasos-vaso-encastra.webp', 'vasos-vaso-encastra', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Fiorent', 59, '/produtos/vasos-vaso-fiorent.webp', 'vasos-vaso-fiorent', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Folha', 59, '/produtos/vasos-vaso-folha.webp', 'vasos-vaso-folha', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Lunara', 59, '/produtos/vasos-vaso-lunara.webp', 'vasos-vaso-lunara', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Moderno', 59, '/produtos/vasos-vaso-moderno.webp', 'vasos-vaso-moderno', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Orbis', 59, '/produtos/vasos-vaso-orbis.webp', 'vasos-vaso-orbis', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Serenidade', 59, '/produtos/vasos-vaso-serenidade.webp', 'vasos-vaso-serenidade', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso SilkFlow', 59, '/produtos/vasos-vaso-silkflow.webp', 'vasos-vaso-silkflow', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Trama', 59, '/produtos/vasos-vaso-trama.png', 'vasos-vaso-trama', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso Trunklin', 59, '/produtos/vasos-vaso-trunklin.webp', 'vasos-vaso-trunklin', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso em forma de U com estampa floral', 59, '/produtos/vasos-vaso-em-forma-de-u-com-estampa-floral.webp', 'vasos-vaso-em-forma-de-u-com-estampa-floral', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso em formato de concha', 59, '/produtos/vasos-vaso-em-formato-de-concha.webp', 'vasos-vaso-em-formato-de-concha', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso escultural espiral moderno', 59, '/produtos/vasos-vaso-escultural-espiral-moderno.png', 'vasos-vaso-escultural-espiral-moderno', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso espiral 1', 59, '/produtos/vasos-vaso-espiral-1.webp', 'vasos-vaso-espiral-1', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso espiral 2', 59, '/produtos/vasos-vaso-espiral-2.webp', 'vasos-vaso-espiral-2', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso espisal 3', 59, '/produtos/vasos-vaso-espisal-3.webp', 'vasos-vaso-espisal-3', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso espisal 4', 59, '/produtos/vasos-vaso-espisal-4.webp', 'vasos-vaso-espisal-4', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso minimalista em U', 59, '/produtos/vasos-vaso-minimalista-em-u.webp', 'vasos-vaso-minimalista-em-u', 'PLA'),
  ((select id from categorias where nome='Vasos'), 'Vaso triangular', 59, '/produtos/vasos-vaso-triangular.webp', 'vasos-vaso-triangular', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Conjunto de Luminárias de Mesa', 149, '/produtos/luminarias-conjunto-de-luminarias-de-mesa.webp', 'luminarias-conjunto-de-luminarias-de-mesa', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Grande Luminária de Parede Luar Iluminado', 149, '/produtos/luminarias-grande-luminaria-de-parede-luar-iluminado.webp', 'luminarias-grande-luminaria-de-parede-luar-iluminado', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária Ariel', 149, '/produtos/luminarias-luminaria-ariel.webp', 'luminarias-luminaria-ariel', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária Ciclone', 149, '/produtos/luminarias-luminaria-ciclone.webp', 'luminarias-luminaria-ciclone', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária Cogumelo Canelado', 149, '/produtos/luminarias-luminaria-cogumelo-canelado.webp', 'luminarias-luminaria-cogumelo-canelado', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária Diamante', 149, '/produtos/luminarias-luminaria-diamante.png', 'luminarias-luminaria-diamante', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária Lua com Base Ondulada', 149, '/produtos/luminarias-luminaria-lua-com-base-ondulada.webp', 'luminarias-luminaria-lua-com-base-ondulada', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária Zephyr', 149, '/produtos/luminarias-luminaria-zephyr.webp', 'luminarias-luminaria-zephyr', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Luminária retrô triangular', 149, '/produtos/luminarias-luminaria-retro-triangular.webp', 'luminarias-luminaria-retro-triangular', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'Orbix Vintage', 149, '/produtos/luminarias-orbix-vintage.webp', 'luminarias-orbix-vintage', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'abajur ondulado', 149, '/produtos/luminarias-abajur-ondulado.webp', 'luminarias-abajur-ondulado', 'PLA'),
  ((select id from categorias where nome='Luminárias'), 'abajur ondulado 2', 149, '/produtos/luminarias-abajur-ondulado-2.webp', 'luminarias-abajur-ondulado-2', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Buldog', 79, '/produtos/animais-buldog.webp', 'animais-buldog', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Busto de Lobo', 79, '/produtos/animais-busto-de-lobo.webp', 'animais-busto-de-lobo', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Busto de Lobo com Entrelaçados Celtas e Runas', 79, '/produtos/animais-busto-de-lobo-com-entrelacados-celtas-e-runas.webp', 'animais-busto-de-lobo-com-entrelacados-celtas-e-runas', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Cachorro', 79, '/produtos/animais-cachorro.webp', 'animais-cachorro', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Camaleão', 79, '/produtos/animais-camaleao.webp', 'animais-camaleao', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Cavalo', 79, '/produtos/animais-cavalo.webp', 'animais-cavalo', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Cavalo imponente de crina larga', 79, '/produtos/animais-cavalo-imponente-de-crina-larga.webp', 'animais-cavalo-imponente-de-crina-larga', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Cavalos em disputa', 79, '/produtos/animais-cavalos-em-disputa.webp', 'animais-cavalos-em-disputa', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Coruja', 79, '/produtos/animais-coruja.webp', 'animais-coruja', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Elefante Minimalista', 79, '/produtos/animais-elefante-minimalista.webp', 'animais-elefante-minimalista', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Escultura Leão', 79, '/produtos/animais-escultura-leao.webp', 'animais-escultura-leao', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Escultura Águia', 79, '/produtos/animais-escultura-aguia.webp', 'animais-escultura-aguia', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Escultura Águia 2', 79, '/produtos/animais-escultura-aguia-2.webp', 'animais-escultura-aguia-2', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Escultura Águia 3', 79, '/produtos/animais-escultura-aguia-3.webp', 'animais-escultura-aguia-3', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Estatueta Cavalo', 79, '/produtos/animais-estatueta-cavalo.webp', 'animais-estatueta-cavalo', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Estatueta Cavalo 2', 79, '/produtos/animais-estatueta-cavalo-2.webp', 'animais-estatueta-cavalo-2', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Estátua Decorativa Detalhada Águia Majestosa sobre Rocha', 79, '/produtos/animais-estatua-decorativa-detalhada-aguia-majestosa-sobre-rocha.webp', 'animais-estatua-decorativa-detalhada-aguia-majestosa-sobre-rocha', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Estátua Leão', 79, '/produtos/animais-estatua-leao.webp', 'animais-estatua-leao', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Gato Polígono', 79, '/produtos/animais-gato-poligono.webp', 'animais-gato-poligono', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Leão e filhote', 79, '/produtos/animais-leao-e-filhote.webp', 'animais-leao-e-filhote', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Lobo', 79, '/produtos/animais-lobo.webp', 'animais-lobo', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Lobo 2', 79, '/produtos/animais-lobo-2.webp', 'animais-lobo-2', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Lobo Estiloso', 79, '/produtos/animais-lobo-estiloso.webp', 'animais-lobo-estiloso', 'PLA'),
  ((select id from categorias where nome='Animais'), 'Puma', 79, '/produtos/animais-puma.webp', 'animais-puma', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Anjo', 89, '/produtos/estatuas-anjo.webp', 'estatuas-anjo', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Busto Cleópatra', 89, '/produtos/estatuas-busto-cleopatra.webp', 'estatuas-busto-cleopatra', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Busto Faraó', 89, '/produtos/estatuas-busto-farao.webp', 'estatuas-busto-farao', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Busto deusa Atena', 89, '/produtos/estatuas-busto-deusa-atena.webp', 'estatuas-busto-deusa-atena', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Casal', 89, '/produtos/estatuas-casal.webp', 'estatuas-casal', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Cristo Crucificado', 89, '/produtos/estatuas-cristo-crucificado.webp', 'estatuas-cristo-crucificado', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Escultuta Duas Faces', 89, '/produtos/estatuas-escultuta-duas-faces.webp', 'estatuas-escultuta-duas-faces', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Estátua', 89, '/produtos/estatuas-estatua.webp', 'estatuas-estatua', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Estátua Romana', 89, '/produtos/estatuas-estatua-romana.webp', 'estatuas-estatua-romana', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Estátua busto feminino', 89, '/produtos/estatuas-estatua-busto-feminino.webp', 'estatuas-estatua-busto-feminino', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Estátua de Buda Sentado', 89, '/produtos/estatuas-estatua-de-buda-sentado.webp', 'estatuas-estatua-de-buda-sentado', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Estátua de Deusa Grega Antiga', 89, '/produtos/estatuas-estatua-de-deusa-grega-antiga.webp', 'estatuas-estatua-de-deusa-grega-antiga', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Estátua moderna', 89, '/produtos/estatuas-estatua-moderna.webp', 'estatuas-estatua-moderna', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'In love', 89, '/produtos/estatuas-in-love.webp', 'estatuas-in-love', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'O Pensador', 89, '/produtos/estatuas-o-pensador.webp', 'estatuas-o-pensador', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Via Crucis', 89, '/produtos/estatuas-via-crucis.webp', 'estatuas-via-crucis', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Virdem de Lourdes', 89, '/produtos/estatuas-virdem-de-lourdes.webp', 'estatuas-virdem-de-lourdes', 'PLA'),
  ((select id from categorias where nome='Estátuas'), 'Zeus', 89, '/produtos/estatuas-zeus.webp', 'estatuas-zeus', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Café', 69, '/produtos/quadros-cafe.webp', 'quadros-cafe', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Elementos', 69, '/produtos/quadros-elementos.webp', 'quadros-elementos', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Lobo', 69, '/produtos/quadros-lobo.webp', 'quadros-lobo', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Lobo com montanha ao fundo', 69, '/produtos/quadros-lobo-com-montanha-ao-fundo.webp', 'quadros-lobo-com-montanha-ao-fundo', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Mapa Mundi Hexagonal', 69, '/produtos/quadros-mapa-mundi-hexagonal.webp', 'quadros-mapa-mundi-hexagonal', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Montanhas', 69, '/produtos/quadros-montanhas.webp', 'quadros-montanhas', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Montanhas 2', 69, '/produtos/quadros-montanhas-2.webp', 'quadros-montanhas-2', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Muheres africanas', 69, '/produtos/quadros-muheres-africanas.webp', 'quadros-muheres-africanas', 'PLA'),
  ((select id from categorias where nome='Quadros'), 'Pássaros', 69, '/produtos/quadros-passaros.webp', 'quadros-passaros', 'PLA'),
  ((select id from categorias where nome='Organizadores'), 'Organizador Cápsulas de Café', 39, '/produtos/organizadores-organizador-capsulas-de-cafe.webp', 'organizadores-organizador-capsulas-de-cafe', 'PLA'),
  ((select id from categorias where nome='Organizadores'), 'Organizador Discos de Algodão e Cotonetes', 39, '/produtos/organizadores-organizador-discos-de-algodao-e-cotonetes.webp', 'organizadores-organizador-discos-de-algodao-e-cotonetes', 'PLA'),
  ((select id from categorias where nome='Organizadores'), 'Suporte HeadPhone', 39, '/produtos/organizadores-suporte-headphone.webp', 'organizadores-suporte-headphone', 'PLA'),
  ((select id from categorias where nome='Organizadores'), 'Suporte HeadPhone 2', 39, '/produtos/organizadores-suporte-headphone-2.webp', 'organizadores-suporte-headphone-2', 'PLA'),
  ((select id from categorias where nome='Presentes'), 'Caixa Expositora de Whisky', 69, '/produtos/presentes-caixa-expositora-de-whisky.webp', 'presentes-caixa-expositora-de-whisky', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso Canaletato', 69, '/produtos/vasos-de-plantas-vaso-canaletato.webp', 'vasos-de-plantas-vaso-canaletato', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de Plantas Triangular Grande Canelado', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-triangular-grande-canelado.webp', 'vasos-de-plantas-vaso-de-plantas-triangular-grande-canelado', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas baixo', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-baixo.webp', 'vasos-de-plantas-vaso-de-plantas-baixo', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas com nervuras curvas e lisas', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-com-nervuras-curvas-e-lisas.webp', 'vasos-de-plantas-vaso-de-plantas-com-nervuras-curvas-e-lisas', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas cúbico arredondado com nervuras', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-cubico-arredondado-com-nervuras.webp', 'vasos-de-plantas-vaso-de-plantas-cubico-arredondado-com-nervuras', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras 2', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-2.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-2', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras 3', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-3.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-3', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras 4', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-4.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-4', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras 5', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-5.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-5', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras 6', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-6.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-6', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno com nervuras 7', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-7.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-7', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de plantas moderno ondulado', 69, '/produtos/vasos-de-plantas-vaso-de-plantas-moderno-ondulado.webp', 'vasos-de-plantas-vaso-de-plantas-moderno-ondulado', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido', 69, '/produtos/vasos-de-plantas-vaso-de-tecido.webp', 'vasos-de-plantas-vaso-de-tecido', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 2', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-2.webp', 'vasos-de-plantas-vaso-de-tecido-2', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 3', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-3.webp', 'vasos-de-plantas-vaso-de-tecido-3', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 4', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-4.webp', 'vasos-de-plantas-vaso-de-tecido-4', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 5', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-5.webp', 'vasos-de-plantas-vaso-de-tecido-5', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 6', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-6.webp', 'vasos-de-plantas-vaso-de-tecido-6', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 7', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-7.webp', 'vasos-de-plantas-vaso-de-tecido-7', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 8', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-8.webp', 'vasos-de-plantas-vaso-de-tecido-8', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso de tecido 9', 69, '/produtos/vasos-de-plantas-vaso-de-tecido-9.webp', 'vasos-de-plantas-vaso-de-tecido-9', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso design torcido', 69, '/produtos/vasos-de-plantas-vaso-design-torcido.webp', 'vasos-de-plantas-vaso-design-torcido', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso estilo Moderno', 69, '/produtos/vasos-de-plantas-vaso-estilo-moderno.webp', 'vasos-de-plantas-vaso-estilo-moderno', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso estilo Moderno 2', 69, '/produtos/vasos-de-plantas-vaso-estilo-moderno-2.webp', 'vasos-de-plantas-vaso-estilo-moderno-2', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso retangular com suporte', 69, '/produtos/vasos-de-plantas-vaso-retangular-com-suporte.webp', 'vasos-de-plantas-vaso-retangular-com-suporte', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso zig-zag', 69, '/produtos/vasos-de-plantas-vaso-zig-zag.webp', 'vasos-de-plantas-vaso-zig-zag', 'PLA'),
  ((select id from categorias where nome='Vasos de plantas'), 'Vaso zig-zag 2', 69, '/produtos/vasos-de-plantas-vaso-zig-zag-2.webp', 'vasos-de-plantas-vaso-zig-zag-2', 'PLA');
