import type { Categoria, Produto } from './supabase'

// GERADO por gen_produtos.py a partir da pasta Segmentos. Nao editar a mao.
export const demoCategorias: Categoria[] = [
  { id: "c-vasos", nome: "Vasos", ordem: 1, ativo: true },
  { id: "c-luminarias", nome: "Luminárias", ordem: 2, ativo: true },
  { id: "c-animais", nome: "Animais", ordem: 3, ativo: true },
  { id: "c-estatuas", nome: "Estátuas", ordem: 4, ativo: true },
  { id: "c-presentes", nome: "Presentes", ordem: 5, ativo: true },
  { id: "c-vasos-de-plantas", nome: "Vasos de plantas", ordem: 6, ativo: true },
]

const base = { descricao: null as string | null, sku: null as string | null, material: 'PLA', peso_g: 150, comprimento_cm: 15, largura_cm: 12, altura_cm: 12, estoque: null as number | null, ativo: true, ordem: 0 }
const P = (o: Pick<Produto,'id'|'nome'|'preco'|'categoria_id'|'foto_url'> & Partial<Produto>): Produto => ({ ...base, ...o })

export const demoProdutos: Produto[] = [
  P({ id: "vasos-nova-pasta", categoria_id: "c-vasos", nome: "Nova pasta", preco: 59, foto_url: "/produtos/vasos-nova-pasta.webp" }),
  P({ id: "vasos-vase-vorticia", categoria_id: "c-vasos", nome: "Vase Vorticia", preco: 59, foto_url: "/produtos/vasos-vase-vorticia.webp" }),
  P({ id: "vasos-vaso", categoria_id: "c-vasos", nome: "Vaso", preco: 59, foto_url: "/produtos/vasos-vaso.webp" }),
  P({ id: "vasos-vaso-2", categoria_id: "c-vasos", nome: "Vaso 2", preco: 59, foto_url: "/produtos/vasos-vaso-2.webp" }),
  P({ id: "vasos-vaso-3", categoria_id: "c-vasos", nome: "Vaso 3", preco: 59, foto_url: "/produtos/vasos-vaso-3.webp" }),
  P({ id: "vasos-vaso-4", categoria_id: "c-vasos", nome: "Vaso 4", preco: 59, foto_url: "/produtos/vasos-vaso-4.webp" }),
  P({ id: "vasos-vaso-axis", categoria_id: "c-vasos", nome: "Vaso Axis", preco: 59, foto_url: "/produtos/vasos-vaso-axis.webp" }),
  P({ id: "vasos-vaso-brisa", categoria_id: "c-vasos", nome: "Vaso Brisa", preco: 59, foto_url: "/produtos/vasos-vaso-brisa.webp" }),
  P({ id: "vasos-vaso-diamante", categoria_id: "c-vasos", nome: "Vaso Diamante", preco: 59, foto_url: "/produtos/vasos-vaso-diamante.webp" }),
  P({ id: "vasos-vaso-diara", categoria_id: "c-vasos", nome: "Vaso Diara", preco: 59, foto_url: "/produtos/vasos-vaso-diara.webp" }),
  P({ id: "vasos-vaso-encastra", categoria_id: "c-vasos", nome: "Vaso Encastra", preco: 59, foto_url: "/produtos/vasos-vaso-encastra.webp" }),
  P({ id: "vasos-vaso-fiorent", categoria_id: "c-vasos", nome: "Vaso Fiorent", preco: 59, foto_url: "/produtos/vasos-vaso-fiorent.webp" }),
  P({ id: "vasos-vaso-folha", categoria_id: "c-vasos", nome: "Vaso Folha", preco: 59, foto_url: "/produtos/vasos-vaso-folha.webp" }),
  P({ id: "vasos-vaso-lunara", categoria_id: "c-vasos", nome: "Vaso Lunara", preco: 59, foto_url: "/produtos/vasos-vaso-lunara.webp" }),
  P({ id: "vasos-vaso-moderno", categoria_id: "c-vasos", nome: "Vaso Moderno", preco: 59, foto_url: "/produtos/vasos-vaso-moderno.webp" }),
  P({ id: "vasos-vaso-orbis", categoria_id: "c-vasos", nome: "Vaso Orbis", preco: 59, foto_url: "/produtos/vasos-vaso-orbis.webp" }),
  P({ id: "vasos-vaso-serenidade", categoria_id: "c-vasos", nome: "Vaso Serenidade", preco: 59, foto_url: "/produtos/vasos-vaso-serenidade.webp" }),
  P({ id: "vasos-vaso-silkflow", categoria_id: "c-vasos", nome: "Vaso SilkFlow", preco: 59, foto_url: "/produtos/vasos-vaso-silkflow.webp" }),
  P({ id: "vasos-vaso-trama", categoria_id: "c-vasos", nome: "Vaso Trama", preco: 59, foto_url: "/produtos/vasos-vaso-trama.png" }),
  P({ id: "vasos-vaso-trunklin", categoria_id: "c-vasos", nome: "Vaso Trunklin", preco: 59, foto_url: "/produtos/vasos-vaso-trunklin.webp" }),
  P({ id: "vasos-vaso-em-forma-de-u-com-estampa-floral", categoria_id: "c-vasos", nome: "Vaso em forma de U com estampa floral", preco: 59, foto_url: "/produtos/vasos-vaso-em-forma-de-u-com-estampa-floral.webp" }),
  P({ id: "vasos-vaso-em-formato-de-concha", categoria_id: "c-vasos", nome: "Vaso em formato de concha", preco: 59, foto_url: "/produtos/vasos-vaso-em-formato-de-concha.webp" }),
  P({ id: "vasos-vaso-escultural-espiral-moderno", categoria_id: "c-vasos", nome: "Vaso escultural espiral moderno", preco: 59, foto_url: "/produtos/vasos-vaso-escultural-espiral-moderno.png" }),
  P({ id: "vasos-vaso-espiral-1", categoria_id: "c-vasos", nome: "Vaso espiral 1", preco: 59, foto_url: "/produtos/vasos-vaso-espiral-1.webp" }),
  P({ id: "vasos-vaso-espiral-2", categoria_id: "c-vasos", nome: "Vaso espiral 2", preco: 59, foto_url: "/produtos/vasos-vaso-espiral-2.webp" }),
  P({ id: "vasos-vaso-espisal-3", categoria_id: "c-vasos", nome: "Vaso espisal 3", preco: 59, foto_url: "/produtos/vasos-vaso-espisal-3.webp" }),
  P({ id: "vasos-vaso-espisal-4", categoria_id: "c-vasos", nome: "Vaso espisal 4", preco: 59, foto_url: "/produtos/vasos-vaso-espisal-4.webp" }),
  P({ id: "vasos-vaso-minimalista-em-u", categoria_id: "c-vasos", nome: "Vaso minimalista em U", preco: 59, foto_url: "/produtos/vasos-vaso-minimalista-em-u.webp" }),
  P({ id: "vasos-vaso-triangular", categoria_id: "c-vasos", nome: "Vaso triangular", preco: 59, foto_url: "/produtos/vasos-vaso-triangular.webp" }),
  P({ id: "luminarias-conjunto-de-luminarias-de-mesa", categoria_id: "c-luminarias", nome: "Conjunto de Luminárias de Mesa", preco: 149, foto_url: "/produtos/luminarias-conjunto-de-luminarias-de-mesa.webp" }),
  P({ id: "luminarias-grande-luminaria-de-parede-luar-iluminado", categoria_id: "c-luminarias", nome: "Grande Luminária de Parede Luar Iluminado", preco: 149, foto_url: "/produtos/luminarias-grande-luminaria-de-parede-luar-iluminado.webp" }),
  P({ id: "luminarias-luminaria-cogumelo-canelado", categoria_id: "c-luminarias", nome: "Luminária Cogumelo Canelado", preco: 149, foto_url: "/produtos/luminarias-luminaria-cogumelo-canelado.webp" }),
  P({ id: "luminarias-luminaria-lua-com-base-ondulada", categoria_id: "c-luminarias", nome: "Luminária Lua com Base Ondulada", preco: 149, foto_url: "/produtos/luminarias-luminaria-lua-com-base-ondulada.webp" }),
  P({ id: "luminarias-luminaria-retro-triangular", categoria_id: "c-luminarias", nome: "Luminária retrô triangular", preco: 149, foto_url: "/produtos/luminarias-luminaria-retro-triangular.webp" }),
  P({ id: "luminarias-abajur-ondulado", categoria_id: "c-luminarias", nome: "abajur ondulado", preco: 149, foto_url: "/produtos/luminarias-abajur-ondulado.webp" }),
  P({ id: "luminarias-abajur-ondulado-2", categoria_id: "c-luminarias", nome: "abajur ondulado 2", preco: 149, foto_url: "/produtos/luminarias-abajur-ondulado-2.webp" }),
  P({ id: "animais-buldog", categoria_id: "c-animais", nome: "Buldog", preco: 79, foto_url: "/produtos/animais-buldog.webp" }),
  P({ id: "animais-busto-de-lobo", categoria_id: "c-animais", nome: "Busto de Lobo", preco: 79, foto_url: "/produtos/animais-busto-de-lobo.webp" }),
  P({ id: "animais-busto-de-lobo-com-entrelacados-celtas-e-runas", categoria_id: "c-animais", nome: "Busto de Lobo com Entrelaçados Celtas e Runas", preco: 79, foto_url: "/produtos/animais-busto-de-lobo-com-entrelacados-celtas-e-runas.webp" }),
  P({ id: "animais-cachorro", categoria_id: "c-animais", nome: "Cachorro", preco: 79, foto_url: "/produtos/animais-cachorro.webp" }),
  P({ id: "animais-camaleao", categoria_id: "c-animais", nome: "Camaleão", preco: 79, foto_url: "/produtos/animais-camaleao.webp" }),
  P({ id: "animais-cavalo", categoria_id: "c-animais", nome: "Cavalo", preco: 79, foto_url: "/produtos/animais-cavalo.webp" }),
  P({ id: "animais-cavalo-imponente-de-crina-larga", categoria_id: "c-animais", nome: "Cavalo imponente de crina larga", preco: 79, foto_url: "/produtos/animais-cavalo-imponente-de-crina-larga.webp" }),
  P({ id: "animais-cavalos-em-disputa", categoria_id: "c-animais", nome: "Cavalos em disputa", preco: 79, foto_url: "/produtos/animais-cavalos-em-disputa.webp" }),
  P({ id: "animais-coruja", categoria_id: "c-animais", nome: "Coruja", preco: 79, foto_url: "/produtos/animais-coruja.webp" }),
  P({ id: "animais-elefante-minimalista", categoria_id: "c-animais", nome: "Elefante Minimalista", preco: 79, foto_url: "/produtos/animais-elefante-minimalista.webp" }),
  P({ id: "animais-escultura-leao", categoria_id: "c-animais", nome: "Escultura Leão", preco: 79, foto_url: "/produtos/animais-escultura-leao.webp" }),
  P({ id: "animais-escultura-aguia", categoria_id: "c-animais", nome: "Escultura Águia", preco: 79, foto_url: "/produtos/animais-escultura-aguia.webp" }),
  P({ id: "animais-escultura-aguia-2", categoria_id: "c-animais", nome: "Escultura Águia 2", preco: 79, foto_url: "/produtos/animais-escultura-aguia-2.webp" }),
  P({ id: "animais-escultura-aguia-3", categoria_id: "c-animais", nome: "Escultura Águia 3", preco: 79, foto_url: "/produtos/animais-escultura-aguia-3.webp" }),
  P({ id: "animais-estatueta-cavalo", categoria_id: "c-animais", nome: "Estatueta Cavalo", preco: 79, foto_url: "/produtos/animais-estatueta-cavalo.webp" }),
  P({ id: "animais-estatueta-cavalo-2", categoria_id: "c-animais", nome: "Estatueta Cavalo 2", preco: 79, foto_url: "/produtos/animais-estatueta-cavalo-2.webp" }),
  P({ id: "animais-estatua-decorativa-detalhada-aguia-majestosa-sobre-rocha", categoria_id: "c-animais", nome: "Estátua Decorativa Detalhada Águia Majestosa sobre Rocha", preco: 79, foto_url: "/produtos/animais-estatua-decorativa-detalhada-aguia-majestosa-sobre-rocha.webp" }),
  P({ id: "animais-estatua-leao", categoria_id: "c-animais", nome: "Estátua Leão", preco: 79, foto_url: "/produtos/animais-estatua-leao.webp" }),
  P({ id: "animais-leao-e-filhote", categoria_id: "c-animais", nome: "Leão e filhote", preco: 79, foto_url: "/produtos/animais-leao-e-filhote.webp" }),
  P({ id: "animais-lobo", categoria_id: "c-animais", nome: "Lobo", preco: 79, foto_url: "/produtos/animais-lobo.webp" }),
  P({ id: "animais-lobo-2", categoria_id: "c-animais", nome: "Lobo 2", preco: 79, foto_url: "/produtos/animais-lobo-2.webp" }),
  P({ id: "animais-lobo-estiloso", categoria_id: "c-animais", nome: "Lobo Estiloso", preco: 79, foto_url: "/produtos/animais-lobo-estiloso.webp" }),
  P({ id: "animais-puma", categoria_id: "c-animais", nome: "Puma", preco: 79, foto_url: "/produtos/animais-puma.webp" }),
  P({ id: "estatuas-anjo", categoria_id: "c-estatuas", nome: "Anjo", preco: 89, foto_url: "/produtos/estatuas-anjo.webp" }),
  P({ id: "estatuas-busto-cleopatra", categoria_id: "c-estatuas", nome: "Busto Cleópatra", preco: 89, foto_url: "/produtos/estatuas-busto-cleopatra.webp" }),
  P({ id: "estatuas-busto-farao", categoria_id: "c-estatuas", nome: "Busto Faraó", preco: 89, foto_url: "/produtos/estatuas-busto-farao.webp" }),
  P({ id: "estatuas-busto-deusa-atena", categoria_id: "c-estatuas", nome: "Busto deusa Atena", preco: 89, foto_url: "/produtos/estatuas-busto-deusa-atena.webp" }),
  P({ id: "estatuas-cristo-crucificado", categoria_id: "c-estatuas", nome: "Cristo Crucificado", preco: 89, foto_url: "/produtos/estatuas-cristo-crucificado.webp" }),
  P({ id: "estatuas-estatua", categoria_id: "c-estatuas", nome: "Estátua", preco: 89, foto_url: "/produtos/estatuas-estatua.webp" }),
  P({ id: "estatuas-estatua-romana", categoria_id: "c-estatuas", nome: "Estátua Romana", preco: 89, foto_url: "/produtos/estatuas-estatua-romana.webp" }),
  P({ id: "estatuas-estatua-busto-feminino", categoria_id: "c-estatuas", nome: "Estátua busto feminino", preco: 89, foto_url: "/produtos/estatuas-estatua-busto-feminino.webp" }),
  P({ id: "estatuas-estatua-de-buda-sentado", categoria_id: "c-estatuas", nome: "Estátua de Buda Sentado", preco: 89, foto_url: "/produtos/estatuas-estatua-de-buda-sentado.webp" }),
  P({ id: "estatuas-estatua-de-deusa-grega-antiga", categoria_id: "c-estatuas", nome: "Estátua de Deusa Grega Antiga", preco: 89, foto_url: "/produtos/estatuas-estatua-de-deusa-grega-antiga.webp" }),
  P({ id: "estatuas-via-crucis", categoria_id: "c-estatuas", nome: "Via Crucis", preco: 89, foto_url: "/produtos/estatuas-via-crucis.webp" }),
  P({ id: "estatuas-virdem-de-lourdes", categoria_id: "c-estatuas", nome: "Virdem de Lourdes", preco: 89, foto_url: "/produtos/estatuas-virdem-de-lourdes.webp" }),
  P({ id: "estatuas-zeus", categoria_id: "c-estatuas", nome: "Zeus", preco: 89, foto_url: "/produtos/estatuas-zeus.webp" }),
  P({ id: "presentes-caixa-expositora-de-whisky", categoria_id: "c-presentes", nome: "Caixa Expositora de Whisky", preco: 69, foto_url: "/produtos/presentes-caixa-expositora-de-whisky.webp" }),
  P({ id: "vasos-de-plantas-vaso-canaletato", categoria_id: "c-vasos-de-plantas", nome: "Vaso Canaletato", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-canaletato.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-2", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras 2", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-2.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-3", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras 3", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-3.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-4", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras 4", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-4.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-5", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras 5", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-5.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-6", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras 6", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-6.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-7", categoria_id: "c-vasos-de-plantas", nome: "Vaso de plantas moderno com nervuras 7", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-plantas-moderno-com-nervuras-7.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-tecido", categoria_id: "c-vasos-de-plantas", nome: "Vaso de tecido", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-tecido.webp" }),
  P({ id: "vasos-de-plantas-vaso-de-tecido-2", categoria_id: "c-vasos-de-plantas", nome: "Vaso de tecido 2", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-de-tecido-2.webp" }),
  P({ id: "vasos-de-plantas-vaso-design-torcido", categoria_id: "c-vasos-de-plantas", nome: "Vaso design torcido", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-design-torcido.webp" }),
  P({ id: "vasos-de-plantas-vaso-estilo-moderno", categoria_id: "c-vasos-de-plantas", nome: "Vaso estilo Moderno", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-estilo-moderno.webp" }),
  P({ id: "vasos-de-plantas-vaso-estilo-moderno-2", categoria_id: "c-vasos-de-plantas", nome: "Vaso estilo Moderno 2", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-estilo-moderno-2.webp" }),
  P({ id: "vasos-de-plantas-vaso-zig-zag", categoria_id: "c-vasos-de-plantas", nome: "Vaso zig-zag", preco: 69, foto_url: "/produtos/vasos-de-plantas-vaso-zig-zag.webp" }),
]
